### ISSUE TITLE
Primitive Wurzel bei Diffie-Hellman

### ISSUE THREAD

**Issue by brewormly** [OhmNoobs/KryptoZusammenfassung#1]
Bei Diffie-Hellman muss g keine primitive Wurzel sein...
Ich hab mich bei der [ Anmerkung des Moderators: Achtung: öffentliches Forum ] kommt.

StackOverflow:
https://stackoverflow.com/questions/5656835/generator-gs-requirement-to-be-a-primitive-root-modulo-p-in-the-diffie-hellman

In Knebls Buch meint er: "Let g be a primitve root ..." / Kann man machen, muss aber keine sein...

Danke, dass ihr euch die Mühe macht die Zusammenfassung zu verbessern!

**Comment by hubwoop** [comment]
Hallo, 

dem SO post und der Wkipedia (https://de.wikipedia.org/wiki/Diffie-Hellman-Schl%C3%BCsselaustausch#%E2%80%9EGenerator%E2%80%9C_g) folgend, habe ich das jetzt auf "sollte primitive Wurzel sein, damit das Verfahren sicher ist" geändert.

Vielen Dank für die Verbesserung! Wenn dir noch etwas auffällt freuen wir uns natürlich auch über pull-requests.

Geändert mit commit https://github.com/OhmNoobs/KryptoZusammenfassung/commit/b336e9ec8640a55a5077947d702d0a65638568f6
